### ISSUE TITLE
mongodb_packages_dependencies needs added

### ISSUE THREAD

**Issue by ytjohn** [lesmyrmidons/ansible-role-mongodb#11]
When installing on Ubuntu 16.04 I get a variable error. Even though the tasks defined would be skipped, the include still happens, and fails because the variable is not set.

```
TASK [lesmyrmidons.mongodb : RedHat | Install dependencies packages] ***********
fatal: [web01.lab]: FAILED! => {"failed": true, "msg": "'mongodb_packages_dependencies' is undefined"}
	to retry, use: --limit @/Users/ytjohn/projects/yourtech-ansible/plays/webhost.retry
```

Setting `mongodb_packages_dependencies: []` in my vars allows it to run:

```
TASK [lesmyrmidons.mongodb : Include OS-specific variables.] *******************
ok: [web01.lab]

TASK [lesmyrmidons.mongodb : RedHat | Install dependencies packages] ***********

TASK [lesmyrmidons.mongodb : RedHat | Add source sources] **********************
skipping: [web01.lab]

TASK [lesmyrmidons.mongodb : RedHat | Install Packages] ************************
skipping: [web01.lab] => (item=[])

TASK [lesmyrmidons.mongodb : Debian | Add keys authenticity] *******************
ok: [web01.lab]
```

I might be able to get a PR in, but documenting here for now.

**Comment by lesmyrmidons** [comment]
Hi @ytjohn,
Are you sure your install is Ubuntu ? Because this variable is specific for os RedHat family.
I use this repository to test the installation of my ansible role for Debian, CentOS and Ubuntu : https://github.com/lesmyrmidons/vm-environment-development.

**Comment by ytjohn** [comment]
Yes.  I think what we're seeing is behavior that [changed in ansible 2.0](http://docs.ansible.com/ansible/playbooks_conditionals.html#applying-when-to-roles-and-includes).

> Note that if you have several tasks that all share the same conditional statement, you can affix the conditional to a task include statement as below. All the tasks get evaluated, but the conditional is applied to each and every task:

The tasks get evaluated, which requires the variable to exist. After evaluation, the conditional is applied.


```
ansible -i inventory/ytprod web01.lab -m setup | grep ansible_os_family
        "ansible_os_family": "Debian",
```

I pulled down your development environment. I did strip out all the roles execpt for the mongodb one.

```
TASK [lesmyrmidons.mongodb : Include OS-specific variables.] *******************
task path: /usr/local/etc/ansible/roles/lesmyrmidons.mongodb/tasks/main.yml:4
ok: [machine1] => {
    "ansible_facts": {
        "id_apt_key": "7F0CEB10",
        "mongodb_repository": "deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen",
        "url_apt_key": "http://keyserver.ubuntu.com/pks/lookup?op=get&search="
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "Debian.yml"
        },
        "module_name": "include_vars"
    }
}

TASK [lesmyrmidons.mongodb : RedHat | Install dependencies packages] ***********
task path: /usr/local/etc/ansible/roles/lesmyrmidons.mongodb/tasks/setup-RedHat.yml:3
fatal: [machine1]: FAILED! => {
    "failed": true,
    "msg": "'mongodb_packages_dependencies' is undefined"
}
	to retry, use: --limit @/Users/ytjohn/projects/vm-environment-development/devops/site.retry

PLAY RECAP *********************************************************************
machine1                   : ok=2    changed=0    unreachable=0    failed=1

```

**Comment by ytjohn** [comment]
I solved this locally with a default filter.

```
- name: RedHat | Install dependencies packages
  yum: name={{ item }} state=installed
  with_items: "{{ mongodb_packages_dependencies | default([]) }}"
```

**Comment by lesmyrmidons** [comment]
What version of ansible do you use ? Because this plugin is defined for 2.1 version minimum.

**Comment by ytjohn** [comment]
ansible-playbook 2.2.0.0
