### ISSUE TITLE
Any chance to make this compatible with Ansible 2.2?

### ISSUE THREAD

**Issue by danvaida** [lesmyrmidons/ansible-role-mongodb#5]
It's not a deprecation warning anymore, it simply doesn't resolve:
```
TASK [lesmyrmidons.mongodb : Debian | Install Packages] ************************
failed: [35.156.158.223] (item=[u'mongodb_packages']) => {"failed": true, "item": ["mongodb_packages"], "msg": "No package matching 'mongodb_packages' is available"}
```

I'm willing to make a PR if needed.

Thanks.

**Comment by kartone** [comment]
Hi, any chance to have this solved ? It's a dependency of graylog2 role and it won't work. Thanks.

**Comment by danvaida** [comment]
@lesmyrmidons you could just tag the current master as `1.2.0`, and that would be enough. The right stuff is already in the master branch.

@kartone in graylog's `requirements.yml` file, just remove the version line (or set it to `master`) for this role. that should sort you out.

**Comment by lesmyrmidons** [comment]
Hi @danvaida, @kartone,

Sorry, I have just seen your messages.

I updated the version `1.2.0`.
